services:

  db:
    image: postgres:16.0
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_USER: accounts_service_user
      POSTGRES_PASSWORD: secret!
      POSTGRES_DB: accounts_service_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"

volumes:
  db_data:
